#
# home
#
app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Login:login }
#
# COMUNES
#
actualizarPeriodo:
  path: /periodo/actualizar
  defaults: { _controller: AppBundle:Comun:actualizarPeriodo}
  options:
    expose: true
#
# REMEDY
#
queryRemedy:
  path: /remedy/query
  defaults: { _controller: AppBundle:Remedy:query}
  options:
    expose: true
incidentesByRemedy:
  path: /remedy/imprimir/{id}
  defaults: { _controller: AppBundle:Remedy:imprimir}
  options:
    expose: true
queryCentros:
  path: /remedy/centros/query
  defaults: { _controller: AppBundle:Remedy:queryCentros}
  options:
    expose: true
editCentro:
  path: /remedy/centros/edit/{id}
  defaults: { _controller: AppBundle:Remedy:editCentro}
  options:
    expose: true
queryUsuarioRemedy:
  path: /remedy/usuarioRemedy/query
  defaults: { _controller: AppBundle:Remedy:queryUsuarioRemedy}
  options:
    expose: true
editUsuarioRemedy:
  path: /remedy/usuarioRemedy/edit/{id}
  defaults: { _controller: AppBundle:Remedy:editUsuarioRemedy}
  options:
    expose: true
queryUsuarioRemedyByCentro:
  path: /remedy/usuarioRemedy/query/{id}
  defaults: { _controller: AppBundle:Remedy:queryUsuarioRemedyByCentro}
  options:
    expose: true
deleteUsuarioRemedy:
  path: /remedy/usuarioRemedy/edit
  defaults: { _controller: AppBundle:Remedy:deleteUsuarioRemedy}
  options:
    expose: true
#
# login
#
login:
    path: /login
    defaults: { _controller: AppBundle:Login:login }
login_check:
    path: /login_check
logout:
    path: /logout
#
# cargaFicheros
#
descargaLog:
    path: /cargaFichero/descargaLog/{id}
    defaults: { _controller: AppBundle:CargaFichero:descargaLog}
    options:
       expose: true
cargaFichero:
    path: /cargaFichero/carga
    defaults: { _controller: AppBundle:CargaFichero:carga}
    options:
        expose: true
deleteCargaFichero:
  path: /cargaFichero/carga/{id}
  defaults: { _controller: AppBundle:CargaFichero:delete}
  options:
    expose: true

recargaFichero:
    path: /cargaFichero/recarga/{id}
    defaults: { _controller: AppBundle:CargaFichero:recarga}
    options:
        expose: true
cargaSeguimiento:
  path: /cargaFichero/seguimiento
  defaults: { _controller: AppBundle:CargaFichero:cargaSeguimiento}
  options:
    expose: true
cargaAgrupacion:
  path: /cargaFichero/cargaAgrupacion
  defaults: { _controller: AppBundle:CargaFichero:cargaAgrupacion}
  options:
    expose: true
cargaLineaSeguimiento:
  path: /cargaFichero/lineaSeguimiento
  defaults: { _controller: AppBundle:CargaFichero:cargaLineaSeguimiento}
  options:
    expose: true

queryFichero:
    path: /cargaFicheros/query
    defaults: { _controller: AppBundle:CargaFichero:query}
    options:
        expose: true

cargaFicheroRemedy:
    path: /cargaFicheros/remedy
    defaults: { _controller: AppBundle:CargaFichero:cargaFicheroRemedy}
    options:
        expose: true
#
# CERTIFICADOS DE SERVICIO
#
generarImportes:
    path: /certificadoServicios/importes/{id}
    defaults: { _controller: AppBundle:CertificadoServicios:importes}
    options:
        expose: true
queryCertificadoServicios:
    path: /certificadoServicios/query
    defaults: { _controller: AppBundle:CertificadoServicios:query}
    options:
        expose: true
editCertificadoServicios:
    path: /certificadoServicios/edit/{id}
    defaults: { _controller: AppBundle:CertificadoServicios:edit}
    options:
        expose: true
cerrarCertificado:
    path: /certificadoServicios/cerrar/{id}
    defaults: { _controller: AppBundle:CertificadoServicios:cerrar}
    options:
        expose: true
abrirCertificado:
  path: /certificadoServicios/abrir/{id}
  defaults: { _controller: AppBundle:CertificadoServicios:abrir}
  options:
    expose: true
addCertificadoServicios:
    path: /certificadoServicios/add
    defaults: { _controller: AppBundle:CertificadoServicios:add}
    options:
        expose: true
deleteCertificadoServicios:
    path: /certificadoServicios/delete/{id}
    defaults: { _controller: AppBundle:CertificadoServicios:delete}
    options:
        expose: true
horasCuotaFija:
  path: /certificadoServicios/horasCuotaFija/{id}
  defaults: { _controller: AppBundle:CertificadoServicios:queryHorasCuotaFija}
  options:
    expose: true

imprimirCertificadoServicios:
    path: /report/certificadoServicios/{id}
    defaults: { _controller: AppBundle:Report:imprimirCertificadoServicios}
    options:
        expose: true
penalizaciones:
    path: /report/penalizaciones/{id}
    defaults: { _controller: AppBundle:Report:penalizaciones}
    options:
        expose: true
revisionPenalizaciones:
    path: /certificadoServicios/revisionpenalizaciones/{id}
    defaults: { _controller: AppBundle:CertificadoServicios:revisionPenalizaciones}
    options:
        expose: true
cargaRevisionPenalizaciones:
  path: /certificadoServicios/revisionpenalizaciones/carga/{id}
  defaults: { _controller: AppBundle:CertificadoServicios:cargaRevisionPenalizaciones}
  options:
    expose: true
editPenalizacion:
  path: /certificadoServicios/editpenalizacion/{id}
  defaults: { _controller: AppBundle:CertificadoServicios:editPenalizacion}
  options:
    expose: true

quitarPenalizacion:
  path: /certificadoServicios/quitarPenalizacion/{id}
  defaults: { _controller: AppBundle:CertificadoServicios:quitarPenalizacion}
  options:
    expose: true
activarPenalizacion:
  path: /certificadoServicios/activarPenalizacion/{id}
  defaults: { _controller: AppBundle:CertificadoServicios:activarPenalizacion}
  options:
    expose: true

ajaxPeriodo:
  path: /certificadoServicios/periodo/{idAnyo}
  defaults: { _controller: AppBundle:CertificadoServicios:ajaxPeriodo}
  options:
    expose: true

exportarReaperturas:
  path: /report/exportarReaperturas/{id}
  defaults: { _controller: AppBundle:CertificadoServicios:exportarReaperturas}
  options:
    expose: true

penalizacionesDetalle:
    path: /report/penalizacioneDetalle/{id}
    defaults: { _controller: AppBundle:Report:penalizacionesDetalle}
    options:
        expose: true
queryEncargos:
    path: /certificadoServicios/queryEncargos/{id}
    defaults: { _controller: AppBundle:CertificadoServicios:queryEncargos}
    options:
        expose: true
excluirEncargo:
    path: /certificadoServicios/excluirEncargo/{lineaCertificado_id}
    defaults: { _controller: AppBundle:CertificadoServicios:excluirEncargo}
    options:
        expose: true
incluirEncargo:
    path: /certificadoServicios/incluirEncargo/{id}
    defaults: { _controller: AppBundle:CertificadoServicios:incluirEncargo}
    options:
        expose: true
imprimirActividadSCF:
  path: /report/actividadSCF/{id}
  defaults: { _controller: AppBundle:Report:actividadSCF}
  options:
    expose: true
#
# CONTRATO
#
queryContrato:
  path: /contrato/query
  defaults: { _controller: AppBundle:Contrato:query}
  options:
    expose: true
editContrato:
  path: /contrato/edit/{id}
  defaults: { _controller: AppBundle:Contrato:edit}
  options:
    expose: true
addContrato:
  path: /contrato/add
  defaults: { _controller: AppBundle:Contrato:add}
  options:
    expose: true
editImporteContratoAnualidad:
  path: /contrato/importeAnualidad/edit/{id}
  defaults: { _controller: AppBundle:Contrato:editImporteAnualidad}
  options:
    expose: true
editImporteContrato:
  path: /contrato/importes/edit/{id}
  defaults: { _controller: AppBundle:Contrato:editImportesContrato}
  options:
    expose: true
#
# AGRUPACION
#
queryAgrupacion:
    path: /agrupacion/query
    defaults: { _controller: AppBundle:Agrupacion:query}
    options:
        expose: true
queryAgrupacionBySeguimiento:
  path: /agrupacion/querybyseguimiento/{id}
  defaults: { _controller: AppBundle:Agrupacion:queryBySeguimiento}
  options:
    expose: true
editAgrupacion:
    path: /agrupacion/edit/{id}
    defaults: { _controller: AppBundle:Agrupacion:edit}
    options:
        expose: true
addAgrupacion:
    path: /agrupacion/add
    defaults: { _controller: AppBundle:Agrupacion:add}
    options:
        expose: true
deleteAgrupacion:
    path: /agrupacion/delete/{id}
    defaults: { _controller: AppBundle:Agrupacion:edit}
    options:
        expose: true
exportarAgrupacion:
  path: /agrupacion/exportar/{id}
  defaults: { _controller: AppBundle:Agrupacion:exportar}
  options:
    expose: true

exportarTodo:
  path: /encargo/exportarTodo
  defaults: { _controller: AppBundle:Encargo:exportarTodo}
  options:
    expose: true

#
# LINEA DE SEGUIMIENTO
#
querySeguimiento:
  path: /seguimiento/query
  defaults: { _controller: AppBundle:Seguimiento:query}
  options:
    expose: true
editSeguimiento:
  path: /seguimiento/edit/{id}
  defaults: { _controller: AppBundle:Seguimiento:edit}
  options:
    expose: true
addSeguimiento:
  path: /seguimiento/add
  defaults: { _controller: AppBundle:Seguimiento:add}
  options:
    expose: true
deleteSeguimiento:
  path: /seguimiento/delete/{id}
  defaults: { _controller: AppBundle:Seguimiento:edit}
  options:
    expose: true
exportarSeguimiento:
  path: /seguimiento/exportar/{id}
  defaults: { _controller: AppBundle:Seguimiento:exportar}
  options:
    expose: true

#
# PROYECCTO
#
queryProyecto:
    path: /proyecto/query
    defaults: { _controller: AppBundle:Proyecto:query}
    options:
        expose: true
editProyecto:
    path: /proyecto/edit/{id}
    defaults: { _controller: AppBundle:Proyecto:edit}
    options:
        expose: true
addProyecto:
    path: /proyecto/add
    defaults: { _controller: AppBundle:Proyecto:add}
    options:
        expose: true
addProyectoAgrupacion:
    path: /proyecto/addAgrupacion
    defaults: { _controller: AppBundle:Proyecto:addAgrupacion}
    options:
        expose: true
queryProyectoAgrupacion:
    path: /proyecto/queryAgrupacion/{id}
    defaults: { _controller: AppBundle:Proyecto:queryAgrupacion}
    options:
        expose: true
#
# ENCARGOS
#
queryEncargosAgrupacion:
    path: /encargo/queryByAgrupacion/{idAgrupacion}
    defaults: { _controller: AppBundle:Encargo:queryByAgrupacion}
    options:
        expose: true
queryEncargo:
    path: /encargo/query
    defaults: { _controller: AppBundle:Encargo:query}
    options:
        expose: true
editEncargo:
    path: /encargo/edit/{id}
    defaults: { _controller: AppBundle:Encargo:edit}
    options:
        expose: true
viewEncargoSeco:
  path: /encargo/viewSeco/{id}
  defaults: { _controller: AppBundle:Encargo:viewSeco}
  options:
    expose: true
deleteEncargo:
    path: /encargo/delete/{id}
    defaults: { _controller: AppBundle:Encargo:delete}
    options:
        expose: true
addAnotacionEncargo:
  path: /encargo/addAnotacion/{encargo_id}
  defaults: { _controller: AppBundle:Encargo:addAnotacion}
  options:
    expose: true
editAnotacionEncargo:
  path: /encargo/anotacion/edit/{id}
  defaults: { _controller: AppBundle:Encargo:editAnotacion}
  options:
    expose: true
deleteAnotacionEncargo:
  path: /encargo/anotacion/delete/{id}
  defaults: { _controller: AppBundle:Encargo:deleteAnotacion}
  options:
    expose: true

#
# REPORTS
#
certificadoActividad:
    path: /report/certificadoActividad/{id}
    defaults: { _controller: AppBundle:Report:certificadoActividad}
    options:
        expose: true

NPLFueraANS:
    path: /report/NPLFueraANS
    defaults: { _controller: AppBundle:Report:NPLFueraANS}
    options:
        expose: true

seguimientoNPL:
    path: /report/seguimientoNPL
    defaults: { _controller: AppBundle:Report:seguimientoNPL}
    options:
        expose: true
filtroInformes:
    path: /report/filtroInformes
    defaults: { _controller: AppBundle:Report:filtro}
    options:
        expose: true
encargosAgrupacion:
    path: /report/encargosAgrupacion/{id}
    defaults: { _controller: AppBundle:Report:encargosAgrupacion}
    options:
        expose: true
seguimientoLineaBase:
    path: /report/seguimientoLineaBase
    defaults: { _controller: AppBundle:Report:seguimientoLineaBase}
    options:
        expose: true
seguimientoImportes:
  path: /report/seguimientoImportes
  defaults: { _controller: AppBundle:Report:seguimientoImportes}
  options:
    expose: true
esfuerzoComprometidoEquipoBase:
  path: /report/esfuerzoComprometidoEquipoBase
  defaults: { _controller: AppBundle:Report:esfuerzoComprometidoEquipoBase}
  options:
    expose: true

imprimirInformeSeguimiento:
  path: /report/informeSeguimiento/{seguimiento_id}/{periodo_id}
  defaults: { _controller: AppBundle:Report:informeSeguimiento}
  options:
    expose: true
informeSeguimiento:
  path: /seguimiento/informe/{id}
  defaults: { _controller: AppBundle:Seguimiento:informeSeguimiento}
  options:
    expose: true
planificacionLB:
  path: /report/planificacionLB
  defaults: { _controller: AppBundle:Report:planificacionLB}
  options:
    expose: true
seguimentoPLA:
    path: /report/seguimientoPLA
    defaults: { _controller: AppBundle:Report:seguimientoPLA}
    options:
        expose: true
esfuerzoPLA:
    path: /report/esfuerzoPLA
    defaults: { _controller: AppBundle:Report:esfuerzoPLA}
    options:
        expose: true
esfuerzoNplAplicacion:
    path: /report/esfuerzoNplAplicacion
    defaults: { _controller: AppBundle:Report:esfuerzoNplAplicacion}
    options:
        expose: true

esfuerzoPLAExt:
    path: /report/esfuerzoPLAExt
    defaults: { _controller: AppBundle:Report:esfuerzoPLAExt}
    options:
        expose: true
esfuerzoPLACompromiso:
    path: /report/esfuerzoPLACompromiso
    defaults: { _controller: AppBundle:Report:esfuerzoPLACompromiso}
    options:
        expose: true
incidentesPorCentro:
    path: /report/incidentesPorCentro
    defaults: { _controller: AppBundle:Report:incidentesPorCentro}
    options:
        expose: true
planificacionEB:
    path: /report/planificacionEB
    defaults: { _controller: AppBundle:Report:planificacionEB}
    options:
        expose: true

#
# GESTION DE USUARIOS
#
cambioPassword:
    path:   /usuario/cambioPassword/{id}
    defaults: { _controller: AppBundle:Usuario:CambioPassword}
    options:
        expose: true
queryUsuario:
    path:   /usuario/query
    defaults: { _controller: AppBundle:Usuario:query}
    options:
        expose: true
addUsuario:
    path:   /usuario/add
    defaults: { _controller: AppBundle:Usuario:add}
    options:
        expose: true
editUsuario:
    path:   /usuario/edit/{id}
    defaults: { _controller: AppBundle:Usuario:edit}
    options:
        expose: true
deleteUsuario:
    path:   /usuario/delete/{id} 
    defaults: { _controller: AppBundle:Usuario:delete}
    options:
        expose: true
generarFicheroSeco:
  path:   /fichero/seco/generar
  defaults: {_controller: AppBundle:CargaFichero:generarFicheroSeco}
  options:
    expose: true
#
# ANALISIS DEL SERVICIO
#
queryAnalisisServicio:
  path:   /analisisServicio/query
  defaults: {_controller: AppBundle:AnalisisServicio:query}
  options:
    expose: true

addAnalisisServicio:
  path:   /analisisServicio/add
  defaults: {_controller: AppBundle:AnalisisServicio:add}
  options:
    expose: true

generaAnalisisServicio:
  path:   /analisisServicio/generar/{periodo_id}
  defaults: {_controller: AppBundle:AnalisisServicio:generaAnalisiServicio}
  options:
    expose: true

queryDetalleAnalisisServicioPeriodo:
  path:   /analisisServicio/detalle
  defaults: {_controller: AppBundle:AnalisisServicio:queryDetalleAnalisisServicioPeriodo}
  options:
    expose: true

ajaxQueryAgrupacionesByLineaSeguimiento:
  path:   /seguimiento/queryAgrupaciones/{seguimiento_id}
  defaults: {_controller: AppBundle:Seguimiento:queryByAgrupaciones}
  options:
    expose: true

selectMes:
      path: /comun/selectMes/{idAnyo}
      defaults: { _controller: AppBundle:Comun:selectMes}
      options:
        expose: true